### ISSUE TITLE
Crash on Updating Text from updateNSView(_ view: NSTextView, context: Context)

### ISSUE THREAD

**Issue by varkrishna** [ChimeHQ/Neon#44] opened 2024-05-05 13:51 UTC
I am using NSTextView in SwiftUI and using **TextViewHighlighter** for Syntax Highlighting. It works well if we dont update the text from `func updateNSView(_ view: JSONEditor, context: Context)` 
but if we do then I am getting a crash everytime 
`Thread 1: Assertion failed: range must not exceed limit` in RangeMutation at line number 24 
(`assert(range.max <= l, "range must not exceed limit")`)

I am pasting the screenshot of call stack
<img width="1458" alt="Screenshot 2024-05-05 at 7 15 29 PM" src="https://github.com/ChimeHQ/Neon/assets/13188037/ec1cd488-3333-494b-9e59-2c3d0e00da64">

<img width="620" alt="Screenshot 2024-05-05 at 7 20 14 PM" src="https://github.com/ChimeHQ/Neon/assets/13188037/1a96cc61-8e32-4863-a5c7-b6c706266b56">

Just let me know if you need anything else from my end to fix this or any idea how to fix this would be a great help.

**Comment by mattmassicotte** [comment] 2024-05-06 11:23
Thank you for reporting this! As a very short-term fix, I *think* you may be able to work around this with a two-step operation:

```swift
view.text = ""
view.text = text
```

I'm going to try to set up a test so I can figure out what's going on.

**Comment by varkrishna** [comment] 2024-05-06 16:53
Hi @mattmassicotte , Thanks for quick reply, really appreciate. Is it possible to explain what's going on, may be I will change my approach till the time this is fixed permanently.

**Comment by mattmassicotte** [comment] 2024-05-07 11:31
The issue is `RangeProcessor.didChangeContent` has a serious bug. This crash will happen if a range is ever changed that is past its maximum processed location. I think this situation can only occur with programmatic text mutation, like what you are doing here. But, I wouldn't be surprised if other paths could lead to this.

To avoid this, you'd have to make sure that the entire content was always processed. And TextViewHighlighter doesn't provide any good API to achieve that. Perhaps by also programmically scrolling to the end first? It's hacky and I don't know if it will work reliably.

**Comment by varkrishna** [comment] 2024-05-07 17:11
Yes, you are right. Programmatically scrolling to bottom to make sure that whole text is processed, preventing the crash. Thanks.

**Comment by mattmassicotte** [comment] 2024-05-10 14:30
I think I have this fixed now. Could you please update to the latest main and try again? And thanks so much for your patience here.

**Comment by varkrishna** [comment] 2024-05-10 18:37
Yes @mattmassicotte , the crash I was getting is fixed not after updating to latest code. Thanks a lot.

**Comment by mattmassicotte** [comment] 2024-05-12 11:39
Wonderful! Thanks again for filing this issue.

**Closed by mattmassicotte** 2024-05-12 11:39 UTC
